### PR TITLE
add check_domain_ping function and elif

### PR DESCRIPTION
**Pull request by peledies**
In some cases, in particular when using PIA as a VPN, the connection will persist and appear to be active but routing stops at the gateway.

This appears to be a `"feature"` of PIA to help protect anonymity.

the `gateway_ping` function is not sufficient in determining if traffic can be routed past the gateway since the gateway does in fact return a response.

By reaching out and pinging a domain, we can see if traffic is able to be routed through the gateway.

### CODE REVIEW

**Comment by beornlake** [comment]
I've also been running into established-but-not-routed connections with our OpenVPN setup, so this looks like a good improvement.

**Comment by beornlake** [comment]
Just wanted to follow-up and say that I've been running this for a couple weeks on a DS620slim and a half dozen DS118's and it's working perfectly. We were having occasional VPN stall-outs previously and haven't had a single stall since implementing the ~`gateway_ping`~ `domain_ping` method.

**Comment by peledies** [comment]
> Just wanted to follow-up and say that I've been running this for a couple weeks on a DS620slim and a half dozen DS118's and it's working perfectly. We were having occasional VPN stall-outs previously and haven't had a single stall since implementing the `gateway_ping` method.

@beornlake do you mean you are having good results with the `domain_ping` method that is introduced with this Merge Request? or the existing `gateway_ping` method?

**Comment by beornlake** [comment]
I do in fact mean `domain_ping`, good catch! (I updated the original comment).

**Comment by jasonkryst** [comment]
Can we get this merged into the master branch? I believe this can make a difference within the project :)

**Review by Forest14 — COMMENTED** [review]
Thanks for posting this! I have been looking for this function.
I would suggest to use something else than Google, why always relying on them?
I have done a bit of research and found out that one of the most reliable services to ping is 
	4.2.2.1 or 4.2.2.2 - https://www.quora.com/What-is-a-4-2-2-1-DNS-server?share=1
Cheers

**Review by Forest14 — COMMENTED** [review]
Hi, wondering what happens with domain ping method if the nslookup fails. What do you think about using a reputable IP address directly instead of going through an NSLOOKUP? 
e.g. Check VPN connection by pinging remote service (4.2.2.2) - https://www.quora.com/What-is-a-4-2-2-1-DNS-server?share=1

**Comment by ianharrier** [comment]
@peledies, thank you for contributing! I just made some modifications (see change notes in https://github.com/ianharrier/synology-scripts/commit/b5029af3744acb9f288b488d6f963fc9dec8f9de) to extend the functionality and condense the code a bit.

One question: was there a specific reason you did an nslookup on the hostname, rather than just pinging the hostname itself?

If you're happy with the modifications I've made, I'll go ahead and merge this into the master branch. Please also make sure your name is correct in the header area of the script. Thanks again!

**Pull request merged**
